#pragma once


enum class EntityType: unsigned int {
	NONE,
	BACKGROUND = 1,
	PLAYER = 2,
	PLATFORM = 4,	
	SPIDERSLIME = 5,
	CHAIR = 7,
	UNITAZ = 8,
	SURGICAL_TABLE = 9,
	METEOROID_GAME_AUTOMATON = 11,
	SLAPAMOLE_GAME_AUTOMATON = 22,
};

